//-----------------------------------------------------------------------
// <copyright file="Binary.cs" company="CompanyName">
//     Company copyright tag.
// </copyright>
//-----------------------------------------------------------------------
namespace LogicalAndJUnit
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Binary class converts the binary to decimal 
    /// then make 2 nibble that is 4-byte
    /// then swap them and find the decimal number of that swap binary number
    /// </summary>
    public class Binary
    {
        /// <summary>
        /// The utility class have the logical part
        /// </summary>
        private readonly Utility utility = new Utility();

        /// <summary>
        /// Converts to convert.
        /// it is convert the binary number to decimal number
        /// </summary>
        public void ToConvert()
        {
            ////take the user input
            Console.WriteLine("Enter number");
            int number = this.utility.ReadInt();

            //// stored the value into the result that is generated by the ToBunary method
            string result = this.utility.ToBinary(number);
            Console.WriteLine("Converted Binary number is : " + result);
            Console.WriteLine(" Makes the Nibble");
            string j = result.PadLeft(9, '0');
            Console.WriteLine("Padded Biary : " + j);

            string nibble1 = result.Substring(0, j.Length / 2);
            string nibble2 = result.Substring(j.Length / 2);
            Console.WriteLine(nibble1);
            Console.WriteLine(nibble2);
            string mergenibble = nibble2 + nibble1;
            Console.WriteLine("swapped Binary is : " + mergenibble);
            int dec = Convert.ToInt32(mergenibble);
            int result1 = this.utility.BinaryToDecimal(dec);
            Console.WriteLine(result1);
        }
    }
}
