//-----------------------------------------------------------------------
// <copyright file="DecimalToBinary.cs" company="CompanyName">
//     Company copyright tag.
// </copyright>
//-----------------------------------------------------------------------
namespace LogicalAndJUnit
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// DecimalToBinary class is makes the binary number
    /// </summary>
    public class DecimalToBinary
    {
        /// <summary>
        /// Binary is the  method that take the user input as decimal and print as binary
        /// </summary>
        public void Binary()
        {
            Utility utility = new Utility();
            ////take the user input
            Console.WriteLine("Enter number");
            int number = utility.ReadInt();
            
            //// stored the value into the result that is generated by the ToBunary method
            string result = utility.ToBinary(number);
            ////print the value
            Console.WriteLine("Converted Binary number is : " + result);
        }
    }
}